
set (_AV_WARE_VERSION_MAJOR 2)
set (_AV_WARE_VERSION_MINOR 2)
set (_AV_WARE_VERSION_PATCH 8)
set (_AV_WARE_VERSION_INWARD 0)
set (_AV_WARE_VERSION_OEM Gp)
set (_AV_WARE_VERSION_RUNTIME RC) #base¡¢alpha¡¢beta ¡¢RC ¡¢ release(R)



#set (COMPILER PC_WIN32)
#set (COMPILER PC_WIN64)
#set (COMPILER PC_LIN32)
#set (COMPILER AMBA)
#set (COMPILER HISI_16C_18ACE_V100)
#set (COMPILER HISI_16C_18E_V200)
set (COMPILER HISI_16AD)
#set (COMPILER HISI_3535)
#set (COMPILER HISI_3536)
#set (COMPILER ALLWINNER_A33)


#set (CMAKE_BUILD_TYPE "Debug")
set (CMAKE_BUILD_TYPE "Release")

##ÏÔÊ¾make ÏêÏ¸ÐÅÏ¢
set (CMAKE_VERBOSE_MAKEFILE ON)

#JSK
set(QT_WIN32_PATH "F:/ProgramTools/Qt/Qt5.7.1X86/5.7/msvc2013")
set(QT_WIN64_PATH "F:/ProgramTools/Qt/Qt5.7.0X64/5.7/msvc2013_64")
set(QT_NVR36_PATH "/opt/hiv300_qt5_6")

#HYD
#set(QT_WIN32_PATH "H:/Qt5.x/5.5/msvc2013")
